/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.4
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "UART_3.h"
#include "PWM_1.h"
#include "UART_4.h"
#include "servo_pwm_aliases.h"
#include "servo_pwm.h"
#include "Clock_1.h"
#include "UART_1.h"
#include "motor_aliases.h"
#include "motor.h"
#include "PWM.h"
#include "Timer.h"
#include "HE_aliases.h"
#include "HE.h"
#include "Clock_0.h"
#include "HE_Interrupt.h"
#include "UART_2.h"
#include "P_front_right_aliases.h"
#include "P_front_right.h"
#include "P_left_1_aliases.h"
#include "P_left_1.h"
#include "P_left_2_aliases.h"
#include "P_left_2.h"
#include "P_right_2_aliases.h"
#include "P_right_2.h"
#include "P_right_1_aliases.h"
#include "P_right_1.h"
#include "P_front_left_aliases.h"
#include "P_front_left.h"
#include "MODE.h"
#include "turn_interrupt.h"
#include "front_right_interrupt.h"
#include "front_left_interrupt.h"
#include "front_interrupt.h"
#include "P_front_aliases.h"
#include "P_front.h"
#include "Clock.h"
#include "STOP.h"
#include "P_back_left_aliases.h"
#include "P_back_left.h"
#include "P_back_aliases.h"
#include "P_back.h"
#include "P_back_right_aliases.h"
#include "P_back_right.h"
#include "back_interrupt.h"
#include "back_left_interrupt.h"
#include "back_right_interrupt.h"
#include "LED.h"
#include "LED_status_aliases.h"
#include "LED_status.h"
#include "UART_3_IntClock.h"
#include "UART_4_IntClock.h"
#include "UART_1_IntClock.h"
#include "UART_2_IntClock.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "cy_em_eeprom.h"

/*[]*/

